### ISSUE TITLE
Try rootlets segmentation on inv2 (MP2RAGE)

### ISSUE THREAD

**Issue by valosekj** [ivadomed/model-spinal-rootlets#45]
Try rootlets segmentation on the inv2 image from an MP2RAGE acquisition.

Ideas: 
- try the contrast translation from @NathanMolinier 
- if the contrast translation does not work, fine-tune the model on the inv2 images directly

**Comment by NathanMolinier** [comment]
I managed to get predictions (using my contrast translation [approach](https://github.com/spinalcordtoolbox/disc-labeling-playground/blob/main/src/ply/inference/run_spineps_inference_with_cGAN.py)) however results are not optimal due to my current resampling to 1 mm isotropic.

|Axial view| Sagittal view|
|:---:|:---:|
| ![Kapture 2024-05-06 at 11 41 16](https://github.com/ivadomed/model-spinal-rootlets/assets/68945192/dac5697c-82a2-443a-9d9a-376645d2f1f7) |![Kapture 2024-05-06 at 11 46 53](https://github.com/ivadomed/model-spinal-rootlets/assets/68945192/b1998a22-749f-4980-85ed-59d15388c6a4) |

**Comment by jcohenadad** [comment]
this is very encouraging though! do you think you could re-train a model that resamples to 0.7mm to see if that helps?

**Comment by NathanMolinier** [comment]
Yes sure ! I will work on that !

**Comment by valosekj** [comment]
> I managed to get predictions (using my contrast translation [approach](https://github.com/spinalcordtoolbox/disc-labeling-playground/blob/main/src/ply/inference/run_spineps_inference_with_cGAN.py)) on a T1w image. 

Very cool, thannks! 

I compared the original and the "fake" image (i.e. created by your contrast translation), and it seems that after contrast translation, we lose the contrast between the rootlets and the CSF:

![Kapture 2024-05-08 at 08 29 57](https://github.com/ivadomed/model-spinal-rootlets/assets/39456460/e39de49c-e15e-46bf-bcce-59b4a0fb793b)

Thus, it is not surprising to me that the rootlets segmentation does not work (as we do not see the rootlets after the contrast translation).

> However results are not optimal due to my current resampling to 1 mm isotropic.

What do you mean by this? When I check the header of the "fake" image, it's still 0.7 mm. Do you mean that the resolution is actually 1 mm (i.e. the header has not been updated)?

**Comment by NathanMolinier** [comment]
No the header is right, but I just perform a resampling to the original resolution at the end of my processing.

So what I mean is that:
- I first resample the input image (0.7mm<sup>3</sup> iso) to 1mm<sup>3</sup> iso
- I perform the contrast translation with the resampled 1mm<sup>3</sup> iso image
- I finally resample the output image to its original resolution (here 0.7mm<sup>3</sup>) which is upsampling in this case.

I think I could technically improve my results for this task if I train the model with a higher resolution. Because I might lose the rootlets when performing my first resampling.

**Comment by valosekj** [comment]
I believe we can close the issue for now.

For a bit of context: 
- we now have not only the `inv2` image but also the `inv1` and `UNIT1` images ([details](https://data.neuro.polymtl.ca/datasets/hc-leipzig-7t-mp2rage/pulls/1))
- the model [r20240523](https://github.com/ivadomed/model-spinal-rootlets/releases/tag/r20240523) trained on T2w images worked reasonably well on `UNIT1` images multiplied by `-1` ([details](https://github.com/ivadomed/model-spinal-rootlets/issues/63))
- @KaterinaKrejci231054 used the [r20240523](https://github.com/ivadomed/model-spinal-rootlets/releases/tag/r20240523) T2w model to segment 5 images from `hc-leipzig-7t-mp2rage` and manually corrected them (details [here](https://github.com/ivadomed/model-spinal-rootlets/pull/64) and [here](https://data.neuro.polymtl.ca/datasets/hc-leipzig-7t-mp2rage/pulls/2))
- we will train a MP2RAGE model, progress will be tracked in https://github.com/ivadomed/model-spinal-rootlets/issues/65
